#!/bin/bash

### BEGIN-SPELL-CHECK
ASPELL=$(which aspell)
if [ $? -ne 0 ]; then
	echo "Aspell not installed – unable to check spelling" >&2
	exit
fi

AWK=$(which awk)
if [ $? -ne 0 ]; then
	echo "Awk not installed – unable to filter spelling errors" >&2
	WORDS=$($ASPELL list < "$1")
else
	WORDS=$($ASPELL --mode=email --add-email-quote='#' list < "$1" | $AWK '!_[$0]++' | tr '\n' '|')
fi

if [ -n "$WORDS" ]; then
	echo ""
	echo "$(tput bold)$(tput setaf 1)Possible spelling errors found in commit message:$(tput sgr0)" >&2
	echo ""
	grep -v '^#' "$1" | sed -e 's/^/   /' | egrep -w --color "${WORDS}\ " >&2
	echo ""
fi
### END-SPELL-CHECK
